---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    ttl: "1"
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    ttl: "1"
spec:
  type: ClusterIP
  ports:
  - port: 3002
    protocol: TCP
  selector:
    name: foo

