apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: karousel
spec:
  replicas: 1
  template:
    metadata:
      name: karousel
      labels:
        app: karousel
    spec:
      serviceAccountName: karousel
      automountServiceAccountToken: true
      containers:
      - name: karousel
        image: mavenlink/karousel:latest
        imagePullPolicy: IfNotPresent
