### cache bust
---
workflows:
  version: 2
  build:
    - build

defaults: &defaults
  working_directory: /home/app/current
  environment: &environment_defaults
    FOO: "bar"
  docker:
    - image: &bootstrap_image 673102273038.dkr.ecr.us-west-2.amazonaws.com/trusty-bootstrap:$CIRCLE_SHA1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: build
          command: |
            set -e
            env
            cd $CIRCLE_WORKING_DIRECTORY
            pwd
            whoami

            docker build -t mavenlink/karousel:$CIRCLE_SHA1 .


            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mavenlink/karousel:$CIRCLE_SHA1
