apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: karousel
spec:
  replicas: 1
  template:
    metadata:
      name: karousel
      labels:
        app: karousel
    spec:
      containers:
      - name: karousel
        image: karousel:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: dockercfgjson
