---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    ttl: "0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        ttl: "0"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
